name: Build Jekyll site

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Zip the site
      run: zip -r site.zip _site

    - name: Upload release asset
      uses: actions/upload-release-asset@v2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./site.zip
        asset_name: site.zip
        asset_content_type: application/zip
